### ISSUE TITLE
Network Synchronization Transactions Not Synchronized

### ISSUE THREAD

**Issue by geeko76** [ConsenSys/ether-pudding#22]
Hi!
I am using ethere-pudding from truffle, and in my private testnet (i use Geth/v1.4.0-unstable/linux/go1.5.1) the transactions never appear as synchronized, the callback is fired immediately (even with no active miner).
I performed some tests and I realized that the issue is at line 288 of index.js:

```javascript
if (tx_info.blockHash != null) {
    clearInterval(interval);
    accept(tx);
}
```

As a matter of fact when a transaction is created on my network, the blockHash is immediately initialized to '0x0':

> eth.getTransaction('0x630fcb406e23e87f15fbc8aca48e8f09411a0cbae50480c7efd7c370d33d3de0').blockHash
"0x0000000000000000000000000000000000000000000000000000000000000000"

Changing the code in:

```javascript
if (tx_info.blockHash != null && tx_info.blockHash != 0x0 ) {
    clearInterval(interval);
    accept(tx);
}
```
ether-pudding starts to behave correctly.

Am I missing something or there was a change in the last version of ethereum regarding the transaction.blockHash management?

Thank you!

Kind regards

Matteo

**Comment by tcoulter** [comment]
Interesting. I'm not sure if there's been a change in geth. Can you show me the javascript code that initiates the transaction that failed?

**Comment by geeko76** [comment]
```javascript
stringTest.setName(name, todayDate, key, {gas: 1000000, value: 10, to: stringTest.address, from: web3.eth.defaultAccount}).then(function(tx_id) {
		document.getElementById('response').innerText = "Success. TXID: " + tx_id;
	}).catch(function(e) {
		document.getElementById('response').innerText = 'Error. ' + e;
	});	
```

**Comment by geeko76** [comment]
Any update on this topic?
Thank you
Matteo

**Comment by area** [comment]
I can confirm that I'm seeing this on `geth` 1.4.0 but not 1.3.6.

**Comment by tcoulter** [comment]
Sorry - had let this one slide. I'll release an update today.

**Comment by tcoulter** [comment]
@geeko76 @area Thanks guys. v2.0.8 pushed to npm. Could one of you verify this fix is correct? Cheers, and sorry for the late response!

**Comment by geeko76** [comment]
Thank you for the fix!
I'll be able to verify it on Monday, 9th (I am currently in NYC attending Consensus Conference...)
I'll keep you posted asap.
Matteo

**Comment by geeko76** [comment]
Sorry for late reply, unfortunately I still see the issue...
