### ISSUE TITLE
ReferenceError: attempts is not defined

### ISSUE THREAD

**Issue by Ryanmtate** [ConsenSys/ether-pudding#31]
Receiving an error from generated .sol.js file. Appears the synchronization function does not instantiate `attempts` variable.

```js
var make_attempt = function() {
  C.web3.eth.getTransactionReceipt(tx, function(err, receipt) {
    if (err) return reject(err);

    if (receipt != null) {
      return accept(tx, receipt);
    }

    if (timeout > 0 && new Date().getTime() - start > timeout) {
      return reject(new Error("Transaction " + tx + " wasn't processed in " + (timeout / 1000) + " seconds!"));
    }

    attempts += 1;

    setTimeout(make_attempt, 1000);
  });
};
```

**Comment by zihehuang** [comment]
Same error happened to me. It seems that the variable's instantiation was removed in this commit: https://github.com/ConsenSys/ether-pudding/commit/4ce5aaa555cc54b29a6bc605bd81bb0f0667d602

**Comment by Schaeff** [comment]
Same here! This error was thrown by metamask but I suspect `ether-pudding` to be responsible

**Comment by tcoulter** [comment]
This has been removed in the latest version! Thanks!
