### ISSUE TITLE
Problem with promisses

### ISSUE THREAD

**Issue by mhhf** [ConsenSys/ether-pudding#4]
I have difficulties to work with Promises:

Every snipped is run in the browser truffle(v0.0.13) env with a fresh chain(testrpc) and contract deployment.
I use the [Coin](https://github.com/ethereum/wiki/wiki/Solidity-Tutorial) Contract from the Solidity Tutorial.

The following web3 code works well:
```
a = web3.eth.accounts[0];
C = web3.eth.contract(Coin.abi);
c = C.at( Coin.deployed_address );
c.mint(a,42);
c.queryBalance( a ); // BigNumber(42)  
```

but the following pudding code never return its promise:
```
a = web3.eth.accounts[0]
c = Coin.at( Coin.deployed_address );
c.mint( a, 42 ).then( function() {
  c.queryBalance(a)
  .then( function( v ){ 
    console.log( v ); // never gets called
  });
})
```
The code works well until the correct balance(42) is received via rpc.
Then suddenly every second the following rpc request is send:

```
{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["42"],"id":5}
```
with following response
```
{"error": {"message": "Invalid parameters.", "code": -32602}, "jsonrpc": "2.0", "id": 5}
```

where to go from here?

**Comment by tcoulter** [comment]
Hi @mhhf. Try this for me:

```
a = web3.eth.accounts[0]
c = Coin.at( Coin.deployed_address );
c.mint( a, 42 ).then( function() {
  return c.queryBalance(a);
}).then( function( v ){ 
  console.log( v ); // never gets called
});
```
If you return a promise with a promise's handler, it will continue executing that promise change. So in this case, `v` will be the return value from `c.queryBalance(a);` (`v` should be a transaction hash since it looks like `queryBalance` is a transaction). Makes sense?

**Comment by tcoulter** [comment]
Edited the comment above; lots of typos.

**Comment by mhhf** [comment]
Works like a charm!

should have read about promises, d'oh!

**Comment by tcoulter** [comment]
Cheers! Let me know if you have anymore questions!
