### ISSUE TITLE
Event filters broken

### ISSUE THREAD

**Issue by chetan** [ConsenSys/ether-pudding#7]
Creating event filters doesn't work in the current NPM release. AFAICT, wrapping contract.allEvents() in a promise doesn't quite work as intended (and also isn't needed). My solution was to simply skip that method as seen here:

https://github.com/chetan/ether-pudding/commit/07418ad0c4582591c69d9c9b91a2a43660db04d6

I was about to submit a PR when I saw  a bunch of refactoring underway. I see some special handling of events but I haven't yet had a chance to test the current version. Any idea if this is fixed in the new implementation?

**Comment by tcoulter** [comment]
Thanks for the bug report. There is a huge refactoring underway. I'll make sure the `allEvents()` function is available.

**Comment by tcoulter** [comment]
`allEvents()` will be present in the latest version set to come out today.
